server:
  port: 8061

eureka:
  server:
    enableSelfPreservation: false
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/